//! A few linear collections built on top of vector.

use core::num::NonZeroUsize;
use std::collections::VecDeque;
use std::ops::{Deref, DerefMut};
use thiserror::Error;

/// A [`CappedQueue`] with fix capacity.
/// The oldest item might be evicted from the queue.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CappedQueue<T> {
    deque: VecDeque<T>,
    capacity: NonZeroUsize,
}

impl<T> CappedQueue<T> {
    /// Create an CappedQueue with the given capacity.
    pub fn new(capacity: NonZeroUsize) -> Self {
        Self { deque: VecDeque::with_capacity(capacity.get()), capacity }
    }

    /// Return the capacity.
    pub fn capacity(&self) -> NonZeroUsize {
        self.capacity
    }

    /// Append an item, remove and return the oldest item if it's full.
    pub fn append(&mut self, i: T) -> Option<T> {
        let to_remove =
            if self.deque.len() == self.capacity.get() { self.deque.pop_front() } else { None };

        self.deque.push_back(i);
        to_remove
    }

    /// Remove the oldest item.
    pub fn pop_front(&mut self) -> Option<T> {
        self.deque.pop_front()
    }

    /// Consumes the queue and returns the queue.
    pub fn into_queue(self) -> VecDeque<T> {
        self.deque
    }
}

impl<T> Deref for CappedQueue<T> {
    type Target = VecDeque<T>;

    fn deref(&self) -> &Self::Target {
        &self.deque
    }
}

impl<T> AsRef<VecDeque<T>> for CappedQueue<T> {
    fn as_ref(&self) -> &VecDeque<T> {
        &self.deque
    }
}

impl<T> From<CappedQueue<T>> for VecDeque<T> {
    fn from(deque: CappedQueue<T>) -> Self {
        deque.deque
    }
}

/// Errors of managing a [`NoneEmptyQue`].
#[derive(Error, Debug, PartialEq, Eq)]
pub enum Error {
    #[error("cannot create NonEmptyQue from empty collection")]
    Empty,
}

/// A queue that contains at least one element.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct NoneEmptyQue<T>(Vec<T>);

impl<T> NoneEmptyQue<T> {
    /// Creates a new [`NoneEmptyQue`] with an initial element.
    pub fn new(e: T) -> Self {
        Self(vec![e])
    }

    /// Creates a new [`NoneEmptyQue`] with a vector without checking, it panics if the
    /// none empty property is broken.
    pub fn from_unchecked(vec: Vec<T>) -> Self {
        assert!(!vec.is_empty(), "NoneEmptyQue::from_unchecked: vector is empty");
        Self(vec)
    }

    /// Returns the num of items in the queue
    pub const fn len(&self) -> NonZeroUsize {
        NonZeroUsize::new(self.0.len()).unwrap()
    }

    /// Returns `true` if the queue contains one element.
    pub const fn is_singleton(&self) -> bool {
        self.0.len() == 1
    }

    /// Returns the 1st item's reference.
    pub fn first(&self) -> &T {
        self.0.first().unwrap()
    }

    /// Returns the 1st item's mutable reference.
    pub fn first_mut(&mut self) -> &mut T {
        self.0.get_mut(0).unwrap()
    }

    /// Returns the last item's reference.
    pub fn last(&self) -> &T {
        self.0.last().unwrap()
    }

    /// Returns the last item's mutable reference.
    pub fn last_mut(&mut self) -> &mut T {
        self.0.last_mut().unwrap()
    }

    /// Maps each element to a new value, preserving the none empty property.
    pub fn map<U, F: FnMut(&T) -> U>(&self, f: F) -> NoneEmptyQue<U> {
        NoneEmptyQue(self.0.iter().map(f).collect())
    }

    /// Consumes the queue and map each item into a new value.
    pub fn map_into<U, F: FnMut(T) -> U>(self, f: F) -> NoneEmptyQue<U> {
        NoneEmptyQue(self.0.into_iter().map(f).collect())
    }

    /// Push an element to the back of the queue
    pub fn push(&mut self, item: T) {
        self.0.push(item);
    }

    /// Inserts an item at position `pos`.
    ///
    /// # Panics
    ///
    /// Panics if `pos > len`.
    pub fn insert(&mut self, pos: usize, item: T) {
        self.0.insert(pos, item);
    }

    /// Extend the queue with the contents of an iterator.
    pub fn extend<I: IntoIterator<Item = T>>(&mut self, iter: I) {
        self.0.extend(iter);
    }

    /// Resizes the queue to the specified length with the specified value if the new_size
    /// is greater than len(), otherwise it truncate the queue when the new_size is less than
    /// len().
    pub fn resize(&mut self, new_size: NonZeroUsize, value: T)
    where
        T: Clone,
    {
        self.0.resize(new_size.get(), value);
    }

    /// Resize the queue to the specified length with the values generated by the closure when
    /// new_size is greater than len(), otherwise it truncate the queue when the new_size is
    /// less than the len().
    pub fn resize_with<F>(&mut self, new_size: NonZeroUsize, f: F)
    where
        F: FnMut() -> T,
    {
        self.0.resize_with(new_size.get(), f)
    }

    /// Removes the last element and returns it, or `None` if there is only one element.
    pub fn pop(&mut self) -> Option<T> {
        if self.0.len() > 1 { self.0.pop() } else { None }
    }

    /// Removes and returns the item at position `pos`, or `None` if removing would leave the queue
    /// empty.
    ///
    /// # Panics
    ///
    /// Panics if the pos is out of bounds.
    pub fn remove(&mut self, pos: usize) -> Option<T> {
        assert!(pos < self.0.len(), "pos out of bounds");
        if self.0.len() > 1 { Some(self.0.remove(pos)) } else { None }
    }

    /// Mutable access to the underlying vector of the queue via a closure.
    ///
    /// # Panics
    ///
    /// Panics if  the closure leaves the underlying vector empty.
    ///
    pub fn mutate<F, R>(&mut self, f: F) -> R
    where
        F: FnOnce(&mut Vec<T>) -> R,
    {
        let r = f(&mut self.0);
        assert!(!self.0.is_empty(), "NoneEmptyQue::mutates: closure left queue empty");

        r
    }

    /// Consumes the queue and returns the underlying vec
    pub fn into_vec(self) -> Vec<T> {
        self.0
    }
}

impl<T> Deref for NoneEmptyQue<T> {
    type Target = [T];
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<T> DerefMut for NoneEmptyQue<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

impl<T> AsRef<[T]> for NoneEmptyQue<T> {
    fn as_ref(&self) -> &[T] {
        &self.0
    }
}

impl<T> AsRef<Vec<T>> for NoneEmptyQue<T> {
    fn as_ref(&self) -> &Vec<T> {
        &self.0
    }
}

impl<T> From<NoneEmptyQue<T>> for Vec<T> {
    fn from(queue: NoneEmptyQue<T>) -> Self {
        queue.0
    }
}

impl<T> TryFrom<Vec<T>> for NoneEmptyQue<T> {
    type Error = Error;

    fn try_from(vec: Vec<T>) -> Result<Self, Self::Error> {
        if vec.is_empty() { Err(Error::Empty) } else { Ok(Self(vec)) }
    }
}

impl<T: Clone> TryFrom<&[T]> for NoneEmptyQue<T> {
    type Error = Error;

    fn try_from(slice: &[T]) -> Result<Self, Self::Error> {
        if slice.is_empty() { Err(Error::Empty) } else { Ok(Self(slice.to_vec())) }
    }
}

impl<T: Clone, const N: usize> TryFrom<[T; N]> for NoneEmptyQue<T> {
    type Error = Error;

    fn try_from(arr: [T; N]) -> Result<Self, Self::Error> {
        if N == 0 { Err(Error::Empty) } else { Ok(Self(arr.into())) }
    }
}

impl<T: Clone, const N: usize> TryFrom<&[T; N]> for NoneEmptyQue<T> {
    type Error = Error;

    fn try_from(arr: &[T; N]) -> Result<Self, Self::Error> {
        Self::try_from(arr.as_slice())
    }
}

impl<T> IntoIterator for NoneEmptyQue<T> {
    type Item = T;
    type IntoIter = <Vec<T> as IntoIterator>::IntoIter;

    fn into_iter(self) -> Self::IntoIter {
        self.0.into_iter()
    }
}

impl<'a, T> IntoIterator for &'a NoneEmptyQue<T> {
    type Item = &'a T;
    type IntoIter = core::slice::Iter<'a, T>;

    fn into_iter(self) -> Self::IntoIter {
        self.0.iter()
    }
}

impl<'a, T> IntoIterator for &'a mut NoneEmptyQue<T> {
    type Item = &'a mut T;
    type IntoIter = core::slice::IterMut<'a, T>;

    fn into_iter(self) -> Self::IntoIter {
        self.0.iter_mut()
    }
}

#[macro_export]
macro_rules! none_empty_queue {
    (@$vec:expr) => {{
        NoneEmptyQue::from_unchecked($vec)
    }};

    ($elem:expr; nz_usize!($n:expr)) => {{
        NoneEmptyQue::from_unchecked(vec![$elem; nz_usize!($n).get()])
    }};

    ($elem:expr; @$n:expr) => {{
        let n: core::num::NonZeroUsize = $n;
        NoneEmptyQue::from_unchecked(vec![$elem; n.get()])
    }};

    ($elem:expr; $n:expr) => {{
        const N: usize = $n;
        const _: () = assert!(N > 0, "count must be greater than 0");
        NoneEmptyQue::from_unchecked(vec![$elem; N])
    }};

    ($first:expr $(, $rest:expr)* $(,)?) => {
        NoneEmptyQue::from_unchecked(vec![$first $(, $rest)*])
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::nz_usize;
    use core::num::NonZeroUsize;

    #[test]
    fn test_capped_evicts_oldest() {
        let mut deque = CappedQueue::new(NonZeroUsize::new(3).unwrap());

        assert_eq!(deque.append(1), None);
        assert_eq!(deque.append(2), None);
        assert_eq!(deque.append(3), None);
        assert_eq!(deque.append(4), Some(1));

        assert_eq!(deque.capacity().get(), 3);
        assert_eq!(deque.iter().copied().collect::<Vec<_>>(), vec![2, 3, 4]);
    }

    #[test]
    fn test_capped_pop_front_reuses_capacity() {
        let mut deque = CappedQueue::new(NonZeroUsize::new(2).unwrap());

        assert_eq!(deque.append(1), None);
        assert_eq!(deque.append(2), None);
        assert_eq!(deque.pop_front(), Some(1));
        assert_eq!(deque.append(3), None);

        assert_eq!(deque.iter().copied().collect::<Vec<_>>(), vec![2, 3]);
    }

    #[test]
    fn test_capped_into_inner() {
        let mut deque = CappedQueue::new(NonZeroUsize::new(2).unwrap());

        deque.append(1);
        deque.append(2);

        assert_eq!(deque.into_queue().into_iter().collect::<Vec<_>>(), vec![1, 2]);
    }

    #[test]
    fn test_new() {
        let v = NoneEmptyQue::new(42);
        assert_eq!(v.len().get(), 1);
        assert_eq!(v.first(), &42);
        assert_eq!(v.last(), &42);
    }

    #[test]
    #[should_panic(expected = "vector is empty")]
    fn test_from_unchecked_panics_on_empty() {
        let _: NoneEmptyQue<i32> = NoneEmptyQue::from_unchecked(vec![]);
    }

    #[test]
    fn test_is_singleton() {
        let v = none_empty_queue![42];
        assert!(v.is_singleton());

        let v = none_empty_queue![1, 2];
        assert!(!v.is_singleton());

        let v = none_empty_queue![1, 2, 3];
        assert!(!v.is_singleton());
    }

    #[test]
    fn test_macro() {
        let v = none_empty_queue![1, 2, 3];
        assert_eq!(v.len().get(), 3);
        assert_eq!(v.first(), &1);
        assert_eq!(v.last(), &3);

        let v = none_empty_queue![42];
        assert_eq!(v.len().get(), 1);
        assert_eq!(v.first(), &42);

        // Trailing comma support
        let v = none_empty_queue![1, 2, 3,];
        assert_eq!(v.len().get(), 3);

        // Const repeat syntax
        let v = none_empty_queue![42; 5];
        assert_eq!(v.len().get(), 5);
        assert!(v.iter().all(|&x| x == 42));

        let v = none_empty_queue![0; 1];
        assert_eq!(v.len().get(), 1);
        assert_eq!(v.first(), &0);

        // NZUsize! macro form
        let v = none_empty_queue![99; nz_usize!(3)];
        assert_eq!(v.len().get(), 3);
        assert!(v.iter().all(|&x| x == 99));

        // Runtime repeat syntax with NonZeroUsize variable
        let n = NonZeroUsize::new(4).unwrap();
        let v = none_empty_queue![7; @n];
        assert_eq!(v.len().get(), 4);
        assert!(v.iter().all(|&x| x == 7));

        // Vec wrap syntax
        let vec = vec![1, 2, 3];
        let v = none_empty_queue![@vec];
        assert_eq!(v.len().get(), 3);
        assert_eq!(&*v, &[1, 2, 3]);
    }

    #[test]
    fn test_try_from_vec() {
        let v: NoneEmptyQue<i32> = vec![1, 2, 3].try_into().unwrap();
        assert_eq!(v.len().get(), 3);

        let result: Result<NoneEmptyQue<i32>, _> = Vec::new().try_into();
        assert_eq!(result, Err(Error::Empty));
    }

    #[test]
    fn test_try_from_slice() {
        let v: NoneEmptyQue<i32> = [1, 2, 3].as_slice().try_into().unwrap();
        assert_eq!(v.len().get(), 3);

        let empty: &[i32] = &[];
        let result: Result<NoneEmptyQue<i32>, _> = empty.try_into();
        assert_eq!(result, Err(Error::Empty));
    }

    #[test]
    fn test_try_from_array() {
        let v: NoneEmptyQue<i32> = [1, 2, 3].try_into().unwrap();
        assert_eq!(v.len().get(), 3);

        let result: Result<NoneEmptyQue<i32>, _> = [0i32; 0].try_into();
        assert_eq!(result, Err(Error::Empty));
    }

    #[test]
    fn test_first_last() {
        let mut v = none_empty_queue![1, 2, 3];

        assert_eq!(v.first(), &1);
        assert_eq!(v.last(), &3);

        *v.first_mut() = 10;
        *v.last_mut() = 30;

        assert_eq!(v.first(), &10);
        assert_eq!(v.last(), &30);
    }

    #[test]
    fn test_push() {
        let mut v = none_empty_queue![1];
        v.push(2);
        v.push(3);
        assert_eq!(v.len().get(), 3);
        assert_eq!(v.last(), &3);
    }

    #[test]
    fn test_insert() {
        let mut v = none_empty_queue![1, 3];
        v.insert(1, 2);
        assert_eq!(&*v, &[1, 2, 3]);
    }

    #[test]
    fn test_extend() {
        let mut v = none_empty_queue![1];
        v.extend([2, 3, 4]);
        assert_eq!(v.len().get(), 4);
        assert_eq!(&*v, &[1, 2, 3, 4]);
    }

    #[test]
    fn test_resize() {
        // Grow
        let mut v = none_empty_queue![1, 2];
        v.resize(NonZeroUsize::new(5).unwrap(), 0);
        assert_eq!(&*v, &[1, 2, 0, 0, 0]);

        // Shrink
        v.resize(NonZeroUsize::new(2).unwrap(), 0);
        assert_eq!(&*v, &[1, 2]);

        // Shrink to 1 (minimum)
        v.resize(NonZeroUsize::new(1).unwrap(), 0);
        assert_eq!(&*v, &[1]);
    }

    #[test]
    fn test_resize_with() {
        let mut counter = 0;
        let mut v = none_empty_queue![1];
        v.resize_with(NonZeroUsize::new(4).unwrap(), || {
            counter += 1;
            counter * 10
        });
        assert_eq!(&*v, &[1, 10, 20, 30]);

        // Shrink (closure not called)
        v.resize_with(NonZeroUsize::new(2).unwrap(), || panic!("should not be called"));
        assert_eq!(&*v, &[1, 10]);
    }

    #[test]
    fn test_pop() {
        let mut v = none_empty_queue![1, 2, 3];

        assert_eq!(v.pop(), Some(3));
        assert_eq!(v.len().get(), 2);

        assert_eq!(v.pop(), Some(2));
        assert_eq!(v.len().get(), 1);

        // Cannot pop the last element
        assert_eq!(v.pop(), None);
        assert_eq!(v.len().get(), 1);
        assert_eq!(v.first(), &1);
    }

    #[test]
    fn test_remove() {
        let mut v = none_empty_queue![1, 2, 3];

        assert_eq!(v.remove(1), Some(2));
        assert_eq!(&*v, &[1, 3]);

        assert_eq!(v.remove(0), Some(1));
        assert_eq!(&*v, &[3]);

        // Cannot remove the last element
        assert_eq!(v.remove(0), None);
        assert_eq!(&*v, &[3]);
    }

    #[test]
    fn test_mutate() {
        let mut v = none_empty_queue![3, 1, 2, 1];
        v.mutate(|vec| {
            vec.sort();
            vec.dedup();
        });
        assert_eq!(&*v, &[1, 2, 3]);

        // Test that return value is propagated
        let mut v = none_empty_queue![1, 2, 3];
        let sum: i32 = v.mutate(|vec| vec.iter().sum());
        assert_eq!(sum, 6);
    }

    #[test]
    #[should_panic(expected = "closure left queue empty")]
    fn test_mutate_panics_on_empty() {
        let mut v = none_empty_queue![1];
        v.mutate(|vec| vec.clear());
    }

    #[test]
    fn test_deref() {
        let v = none_empty_queue![3, 1, 2];

        // slice methods via Deref
        assert_eq!(v.len().get(), 3);
        assert!(v.contains(&2));
        assert_eq!(v.get(1), Some(&1));
    }

    #[test]
    fn test_deref_mut() {
        let mut v = none_empty_queue![3, 1, 2];

        // Mutable slice methods via DerefMut
        v.sort();
        assert_eq!(&*v, &[1, 2, 3]);

        v.reverse();
        assert_eq!(&*v, &[3, 2, 1]);

        v.swap(0, 2);
        assert_eq!(&*v, &[1, 2, 3]);
    }

    #[test]
    fn test_into_vec() {
        let v = none_empty_queue![1, 2, 3];
        let vec: Vec<i32> = v.into_vec();
        assert_eq!(vec, vec![1, 2, 3]);
    }

    #[test]
    fn test_map() {
        let v = none_empty_queue![1, 2, 3];
        let doubled = v.map(|x| x * 2);
        assert_eq!(&*doubled, &[2, 4, 6]);

        // Original unchanged
        assert_eq!(&*v, &[1, 2, 3]);
    }

    #[test]
    fn test_map_into() {
        let v = none_empty_queue![1, 2, 3];
        let doubled = v.map_into(|x| x * 2);
        assert_eq!(&*doubled, &[2, 4, 6]);
    }

    #[test]
    fn test_from_non_empty_vec() {
        let v = none_empty_queue![1, 2, 3];
        let vec: Vec<i32> = v.into();
        assert_eq!(vec, vec![1, 2, 3]);
    }

    #[test]
    fn test_index() {
        let v = none_empty_queue![1, 2, 3];
        assert_eq!(v[0], 1);
        assert_eq!(v[1], 2);
        assert_eq!(v[2], 3);
        assert_eq!(&v[0..2], &[1, 2]);

        // IndexMut
        let mut v = none_empty_queue![1, 2, 3];
        v[0] = 10;
        v[1..3].copy_from_slice(&[20, 30]);
        assert_eq!(&*v, &[10, 20, 30]);
    }

    #[test]
    fn test_iterators() {
        let v = none_empty_queue![1, 2, 3];

        // iter()
        let sum: i32 = v.iter().sum();
        assert_eq!(sum, 6);

        // iter_mut()
        let mut v = none_empty_queue![1, 2, 3];
        for x in v.iter_mut() {
            *x *= 2;
        }
        assert_eq!(&*v, &[2, 4, 6]);

        // IntoIterator (owned)
        let v = none_empty_queue![1, 2, 3];
        let collected: Vec<_> = v.into_iter().collect();
        assert_eq!(collected, vec![1, 2, 3]);

        // IntoIterator (borrowed)
        let v = none_empty_queue![1, 2, 3];
        let collected: Vec<_> = (&v).into_iter().copied().collect();
        assert_eq!(collected, vec![1, 2, 3]);

        // IntoIterator (borrowed mut)
        let mut v = none_empty_queue![1, 2, 3];
        for x in &mut v {
            *x += 10;
        }
        assert_eq!(&*v, &[11, 12, 13]);
    }

    #[test]
    fn test_as_ref() {
        let v = none_empty_queue![1, 2, 3];

        let slice: &[i32] = v.as_ref();
        assert_eq!(slice, &[1, 2, 3]);

        let vec_ref: &Vec<i32> = v.as_ref();
        assert_eq!(vec_ref, &vec![1, 2, 3]);
    }
}
